// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grcuqnwebrrwfplvlpfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyY3VxbndlYnJyd2ZwbHZscGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NzA0NTIsImV4cCI6MjA1NjM0NjQ1Mn0.NpDF-qwZ70D_6yDiywCDfmtz4MZzGG-hewgJGecOUyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);